# Generated by Django 3.2.15 on 2025-08-23 10:36

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeLog',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('flashcard_type', models.CharField(max_length=15)),
                ('flashcard_id', models.CharField(max_length=255)),
                ('action', models.CharField(default='practice_feedback', max_length=50)),
                ('feedback', models.CharField(blank=True, max_length=21, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('meta', djongo.models.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'practice_log',
            },
        ),
        migrations.AddIndex(
            model_name='practicelog',
            index=models.Index(fields=['created_by', 'created_at'], name='practice_lo_created_de9e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='practicelog',
            index=models.Index(fields=['flashcard_id', 'flashcard_type'], name='practice_lo_flashca_9d7a5d_idx'),
        ),
    ]
