# Generated by Django 3.2.15 on 2025-08-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0002_auto_20250823_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicelog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='practicelog',
            name='duration_seconds',
        ),
    ]
