# Generated by Django 3.2.15 on 2025-08-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0003_auto_20250823_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
