# Generated by Django 3.2.15 on 2025-08-29 04:23

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0004_uploadedimage_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='answers',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
