# Generated by Django 3.2.15 on 2025-09-09 07:35

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0005_auto_20250829_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='gridfs_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='labels',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='masks',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
