# Generated by Django 3.2.15 on 2025-09-10 06:45

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0006_auto_20250909_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='labels',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='masks',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
    ]
