# Generated by Django 3.2.15 on 2025-09-10 06:54

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0007_auto_20250910_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='labels',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='masks',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
