# Generated by Django 3.2.15 on 2025-09-12 09:31

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0008_auto_20250910_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicelog',
            name='upload_image_questions',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='practicelog',
            name='meta',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
    ]
