# Generated by Django 3.2.15 on 2025-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0009_auto_20250912_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
