# Generated by Django 3.2.15 on 2025-09-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0010_auto_20250913_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image_width',
        ),
        migrations.AddField(
            model_name='customrolepermission',
            name='can_create_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customrolepermission',
            name='can_delete_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customrolepermission',
            name='can_read_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customrolepermission',
            name='can_update_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='flashcard_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('FIB', 'FIB'), ('SUB', 'SUB'), ('TRUEFALSE', 'TRUEFALSE'), ('IMAGE', 'IMAGE')], max_length=50),
        ),
    ]
